# Generated by Django 2.0.5 on 2018-11-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatecriteria',
            name='creativity',
            field=models.ManyToManyField(blank=True, related_name='creativity', to='lecture.LectureName'),
        ),
        migrations.AddField(
            model_name='graduatecriteria',
            name='language',
            field=models.ManyToManyField(related_name='grad_language', to='lecture.LectureName'),
        ),
        migrations.AddField(
            model_name='graduatecriteria',
            name='major_mandatories',
            field=models.ManyToManyField(related_name='major_mandatory', to='lecture.LectureName'),
        ),
        migrations.AddField(
            model_name='graduatecriteria',
            name='major_optional',
            field=models.ManyToManyField(related_name='major_optional', to='lecture.LectureName'),
        ),
        migrations.AddField(
            model_name='graduatecriteria',
            name='math',
            field=models.ManyToManyField(blank=True, related_name='math', to='lecture.LectureName'),
        ),
        migrations.AddField(
            model_name='graduatecriteria',
            name='science',
            field=models.ManyToManyField(blank=True, related_name='science', to='lecture.LectureName'),
        ),
        migrations.AddField(
            model_name='graduatecriteria',
            name='sociality',
            field=models.ManyToManyField(blank=True, related_name='sociality', to='lecture.LectureName'),
        ),
        migrations.AddField(
            model_name='user',
            name='lecture_opinions',
            field=models.ManyToManyField(blank=True, to='lecture.LectureOpinion'),
        ),
        migrations.AddField(
            model_name='user',
            name='lectures',
            field=models.ManyToManyField(blank=True, to='lecture.LectureName'),
        ),
    ]
